# Generated by Django 3.2.4 on 2022-10-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_measures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chara_id',
            field=models.IntegerField(default=1, verbose_name='キャラクターid'),
            preserve_default=False,
        ),
    ]
